### ISSUE TITLE
Mounting of /eos

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw-osenv#2]
These scripts automatically mount /eos. This might not be desirable in general:
* at FNAL, we discourage use of the FUSE mount because of frequently-observed instabilities: https://uscms.org/uscms_at_work/computing/LPC/usingEOSAtLPC.shtml#doNot
* this also caused a problem for some tests of https://github.com/cms-sw/cmssw/pull/32576, which uses a non-CMS Singularity image whose entrypoint performs `find /`; on lxplus with /eos mounted, this takes forever and spits out many permission denied messages

It would be nice to have some toggle to turn this off or on. Personally, I would prefer if the default were "off", but I am open to rebuttals on that point before making a PR.

**Comment by smuzaffar** [comment]
@kpedro88 , how about a command line option e.g `--ignore-mount path1[,path2[,path3]]` to not mount these paths?

**Comment by kpedro88** [comment]
That would certainly be useful in general.
