### ISSUE TITLE
Install perf in Singularity images

### ISSUE THREAD

**Issue by gartung** [cms-sw/cmssw-osenv#6]
Linux perf can be used to generate output that might be convertable to Igprof format. However I don't find perf in the EL8 Singularity imaged when I run cmssw-el8.

**Comment by smuzaffar** [comment]
done, [perf](https://github.com/cms-sw/cms-docker/commit/3be4202edd5d1388c5b4482d2a4c567c9b037618) is now part of `cmssw/el8` containers

**Comment by gartung** [comment]
How long should it take to propagate the changes to /cvmfs/unpacked.cern.ch/

**Comment by smuzaffar** [comment]
now a days, cvmfs team updates `/cvmfs/unpacked.cern.ch`  once at day at 23h00. @radupopescu can you please force run the unpack job?

**Comment by gartung** [comment]
Is it possible to set this flag in the Singularity image, or is this something that has to be set on the host?
```
perf record -g -- cmsRun step3.py
Error:
Access to performance monitoring and observability operations is limited.
Consider adjusting /proc/sys/kernel/perf_event_paranoid setting to open
access to performance monitoring and observability operations for processes
without CAP_PERFMON, CAP_SYS_PTRACE or CAP_SYS_ADMIN Linux capability.
More information can be found at 'Perf events and tool security' document:
https://www.kernel.org/doc/html/latest/admin-guide/perf-security.html
perf_event_paranoid setting is 4:
  -1: Allow use of (almost) all events by all users
      Ignore mlock limit after perf_event_mlock_kb without CAP_IPC_LOCK
>= 0: Disallow raw and ftrace function tracepoint access
>= 1: Disallow CPU event access
>= 2: Disallow kernel profiling
To make the adjusted perf_event_paranoid setting permanent preserve it
in /etc/sysctl.conf (e.g. kernel.perf_event_paranoid = <setting>)
```

**Comment by gartung** [comment]
Nevermind. I remember now that kernel parameters have to be set on the Singularity host machine.

**Comment by smuzaffar** [comment]
rigth, singularity and docker use system kernel

**Comment by gartung** [comment]
If I recall correctly this parameter is already set for the Jenkins RECO profiling machine and the Jenkins profiling nodes so Vtune can run. Is this correct?

**Comment by smuzaffar** [comment]
I do not remember setting any such flag for profiling nodes

**Comment by radupopescu** [comment]
> now a days, cvmfs team updates `/cvmfs/unpacked.cern.ch` once at day at 23h00. @radupopescu can you please force run the unpack job?

I triggered the job now.

**Comment by gartung** [comment]
> 

For running Vtune some flags needed to be set.

**Comment by smuzaffar** [comment]
@gartung , I would suggest to open a new issue under cms-sw/cmssw
