### ISSUE TITLE
locales missing from el8 and (some) rhel8 containers

### ISSUE THREAD

**Issue by srlantz** [cms-sw/cmssw-osenv#7]
It seems the CMSSW Singularity containers for el8 and (in certain cases) rhel8 are lacking many locales, in particular, en_US.utf-8. For some reason, this causes a problem for icc, the Intel C/C++ Classic Compiler that is now included for free with the Intel oneAPI HPC Toolkit. This compiler could very well be installed on one's host system, and it should be usable for testing purposes in the container. Instead, I find that icc generally exits with an error when one tries to use it for compiling in the container.

I have identified a few workarounds, such as setting the `-no-multibyte-chars` option for icc, or doing `export LC_ALL=C.utf-8` in the shell. However, I believe it would be simpler (and therefore preferable) to make more locales available in the image, as described here: [apptainer/singularity#3765](https://github.com/apptainer/singularity/issues/3765) (the last post in particular).

This is worth opening an issue, I think, and I am hoping this is the right place to do it, even though the issue is perhaps best corrected in the images themselves, and not in the wrapper scripts. You can see that there is an issue in the images by starting up the following two containers with `singularity exec XXX /bin/bash` and comparing the output of `locale -a`:
```
XXX=/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el8:x86_64
XXX=/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/cms:rhel8-m20220516
```
The latter has many, many more locales. But note that `/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/cms:rhel8-m` (without the additional numbers) looks more like `el8:x86_46` in having just a few locales available. Anyway, in the `cms:rhel8-m20220516` container, I find that icc works fine, with no need to `export LC_ALL=C.utf-8` (e.g.).

Without one of the workarounds, the precise error message from icc is: 'Catastrophic error: could not set locale "" to allow processing of multibyte characters'

**Comment by smuzaffar** [comment]
thanks @srlantz for opening ths issue. Looks like default `CentOS Stream 8` container has `glibc-langpack-en` installed while `almalinux8` does not. Both `cmssw/el8` and `cms:rhel8-m` are based on `almalinux8`. I have updated dockerfiles to explicitly install  `glibc-langpack-en`  for `el8 and cms` images. New images will be available tomorrow

**Comment by srlantz** [comment]
Thank you, @smuzaffar, I can confirm that the issue is resolved in the images for both the `el8:x86_64` and the `cms:rhel8-m` containers.
