### ISSUE TITLE
xdg-open missing from cmssw-el8

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw-osenv#9]
When trying to launch a ROOT TBrowser in the cmssw-el8 container, I get the following error message:
```
sh: xdg-open: command not found
```

Can the container be updated to include this (and any other basic graphics packages)? Being able to inspect the output of test workflows is important for development.

**Comment by smuzaffar** [comment]
@kpedro88 , I have installed `xauth xdg-utils` , can you please try cmssw-el8 again?  `root --web=off`  in cmssw-el8 works for me now.

**Comment by kpedro88** [comment]
Thanks, it works now.
